service: service-simple-serverless-back
frameworkVersion: '2 || 3'
app: simple-serverless-back

package:
  patterns:
    - '!node_modules/aws-sdk'
    - '!node_modules/serverless'
    - '!node_modules/@serverless'
    - '!.idea'
    - '!images'
    - '!yarn.lock'
    - '!yarn.error.log'
    - '!README.md'
    - '!.gitignore'
    - '!package.json'
    - '!.git'

custom:
  name: 'simple-serverless-back'
  environment: 'prod'
  region: 'us-east-1'
  bucket: 'service-lambda-thumb-tifig-d-sourcebucketdc914398-10oo755kbh9e8'
  lambda_prefix: ${self:custom.environment}-${self:custom.name}

provider:
  name: aws
  lambdaHashingVersion: '20201221'
  environment:
    S3_BUCKET: ${self:custom.bucket}
    REGION: ${self:custom.region}
  region: ${self:custom.region}
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
      Resource:
        - 'arn:aws:s3:::${self:custom.bucket}'
        - 'arn:aws:s3:::${self:custom.bucket}/*'

functions:
  getS3SignedUrl:
    name: get-s3-signed-url
    handler: index.handler
    events:
      - http:
          method: GET
          path: /
          cors: true
